docs: add secure boot verification
zarhus/docs pull request #10
Opened 2024-09-18 15:08 UTC by m-iwanicki

Rebase and change target to main before merge

2024-09-23 11:50 UTC, pietrushnic commented
@macpijan I wonder what you think about its design. It closely relates to my teaching materials for upcoming hardwear.io and OST2 training.

2024-10-01 21:31 UTC, pietrushnic requested changes

2024-10-02 12:06 UTC, m-iwanicki commented on docs/guides/secure-boot/secure-boot-verification.md
> +        `-drive if=ide,file=tests.img` argument to `qemu` command
Script creates FAT image that contains EFI partition and uses generated UUID later to find correct USB drive and add all `.efi` files to boot options.
If it's mounted as directory then `add-boot-options.sh` would need some changes.

2024-10-04 22:55 UTC, pietrushnic commented on docs/guides/secure-boot/secure-boot-verification.md
> +-->
It looks like that state comes from UEFI Variables. I guess the OS cannot do anything better; maybe expect attesting firmware to present that state.

2024-10-14 15:16 UTC, macpijan commented
> @macpijan I wonder what you think about its design. It closely relates to my teaching materials for upcoming hardwear.io and OST2 training.

I think my main concert was duplication with content from docs.dasharo.com

2024-10-27 22:58 UTC, pietrushnic commented
@macpijan, what would be our preferred way to address the duplication issue? I have to say that the description docs.dasharo.com is outdated and should be corrected. Also, the methodology should be changed not to use UEFI Secure Boot, as done here.

I agree we need some consistency, and maybe this documentation better fits Dasharo as it tests its implementation of OTOH; it should also test OVMF and any proprietary implementation. Finally, I would like to make this implementation a base for future products to assess the quality of UEFI Secure Boot implementation. In that light, what would be the best way to deal with this PR?

2024-10-30 18:17 UTC, artur-rs commented
Merging the documents in this form, as the Dasharo docs sync and test-case update will be prepared in the next phase of this project.

2024-10-30 18:25 UTC, merged